name: Continuous integration

on:
  push:
    branches: ['**']

jobs:
  lint-and-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: sbt

      - run: sbt 'scalafixAll --check' scalafmtSbtCheck scalafmtCheck
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: sbt +test
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
